// Definir las clases de imagenet
export const IMAGENET_CLASSES = {
  0: "tench, Tinca tinca",
  1: "goldfish, Carassius auratus",
  2: "great white shark, Carcharodon carcharias",
  3: "tiger shark, Galeocerdo cuvieri",
  4: "hammerhead, hammerhead shark",
  5: "electric ray, crampfish, numbfish, torpedo",
  6: "stingray",
  7: "cock",
  8: "hen",
  9: "ostrich, Struthio camelus",
  10: "brambling, Fringilla montifringilla",
  11: "goldfinch, Carduelis carduelis",
  12: "house finch, Haemorhous mexicanus",
  13: "junco, snowbird",
  14: "American robin, Turdus migratorius",
  15: "bulbul",
  16: "jay",
  17: "magpie",
  18: "chickadee",
  19: "kingfisher, Alcedo atthis",
  20: "albatross, mollymawk",
  21: "vulture",
  22: "partridge",
  23: "grouse",
  24: "quail",
  25: "European eagle owl, Bubo bubo",
  26: "bald eagle, American eagle, Haliaeetus leucocephalus",
  27: "kite",
  28: "falcon",
  29: "parakeet, parrakeet, budgerigar",
  30: "Australian parrot",
  31: "lorikeet",
  32: "coucal",
  33: "full-grown man",
  34: "cuckoo",
  35: "roadrunner, ground cuckoo, Geococcyx californianus",
  36: "hoatzin, Opisthocomus hoazin",
  37: "starling, Sturnus vulgaris",
  38: "nightingale, Luscinia megarhynchos",
  39: "lark, A-10 Thunderbolt II",
  40: "pigeon, rock dove, rock pigeon, Columba livia",
  41: "guillemot, murre",
  42: "tern",
  43: "ptarmigan",
  44: "water ouzel, dipper",
  45: "egret",
  46: "heron",
  47: "crane, Grus antigone",
  48: "limpkin, Aramus guarauna",
  49: "flamingo",
  50: "spoonbill",
  51: "pelican, Pelecanus",
  52: "king penguin, Aptenodytes patagonica",
  53: "albatross",
  54: "grey whale, gray whale, devilfish, Eschrichtius robustus",
  55: "killer whale, killer, orca, Grampus orca",
  56: "dugong, Dugong dugon",
  57: "sea lion",
  58: "Chihuahua",
  59: "Japanese spaniel",
  60: "Maltese dog, Maltese",
  61: "Pekinese, Pekingese, peke",
  62: "Shih-Tzu",
  63: "Blenheim spaniel, Blenheim",
  64: "papillon",
  65: "toy poodle",
  66: "miniature poodle",
  67: "standard poodle",
  68: "Mexican hairless dog",
  69: "toy terrier",
  70: "Rhodesian ridgeback",
  71: "Afghan hound, Afghan",
  72: "basset, basset hound",
  73: "beagle",
  74: "bloodhound, sleuthhound",
  75: "bluetick",
  76: "black-and-tan coonhound",
  77: "redbone",
  78: "borzoi, Russian wolfhound, Canis lupus familiaris",
  79: "Irish wolfhound",
  80: "Italian greyhound",
  81: "whippet",
  82: "Ibizan hound, Ibizan dog",
  83: "Norwegian elkhound, elkhound",
  84: "otterhound, otter hound",
  85: "Saluki, gazelle hound",
  86: "Scottish deerhound, deerhound",
  87: "Weimaraner",
  88: "Staffordshire bullterrier, Staffordshire bull terrier",
  89: "American Staffordshire terrier, American pit bull terrier, pit bull terrier",
  90: "Bedlington terrier",
  91: "Border terrier",
  92: "Kerry blue terrier",
  93: "Irish terrier",
  94: "Norfolk terrier",
  95: "Norwich terrier, Norwich",
  96: "Yorkshire terrier",
  97: "wire-haired fox terrier",
  98: "Lakeland terrier",
  99: "Sealyham terrier, Sealyham",
  100: "Airedale, Airedale terrier",
  101: "cairn, cairn terrier",
  102: "Australian terrier",
  103: "Dandie Dinmont terrier, Dandie Dinmont",
  104: "Boston terrier",
  105: "Siberian husky",
  106: "schnauzer",
  107: "giant schnauzer",
  108: "standard schnauzer",
  109: "Scotch terrier, Scottish terrier, Scottie",
  110: "West Highland white terrier",
  111: "Tibetan terrier, chrysanthemum dog",
  112: "Lhasa apso",
  113: "flat-coated retriever",
  114: "curly-coated retriever",
  115: "golden retriever",
  116: "Labrador retriever",
  117: "Chesapeake Bay retriever",
  118: "German short-haired pointer",
  119: "vizsla",
  120: "English setter",
  121: "Irish setter, red setter",
  122: "Gordon setter",
  123: "Brittany spaniel",
  124: "clumber, clumber spaniel",
  125: "cocker spaniel, English cocker spaniel, American cocker spaniel, cocker",
  126: "Sussex spaniel",
  127: "Irish water spaniel",
  128: "kuvasz",
  129: "schipperke",
  130: "groenendael",
  131: "malinois",
  132: "briard",
  133: "komondor",
  134: "Old English sheepdog, bobtail",
  135: "Shetland sheepdog, Shetland sheep dog, Sheltie",
  136: "collie",
  137: "Border collie",
  138: "Bouvier des Flandres, Bouviers des Flandres",
  139: "Rottweiler",
  140: "German shepherd dog, German shepherd, German police dog, Alsatian",
  141: "Doberman, Doberman pinscher",
  142: "miniature pinscher",
  143: "Greater Swiss Mountain dog",
  144: "Bernese mountain dog",
  145: "Appenzeller",
  146: "entlebucher",
  147: "boxer",
  148: "bull mastiff",
  149: "Tibetan mastiff",
  150: "French bulldog",
  151: "great dane",
  152: "Saint Bernard, St Bernard, St. Bernard",
  153: "husky",
  154: "malamute, Malemute, Alaskan malamute",
  155: "Siberian husky",
  156: "dalmatian",
  157: "Affenpinscher, monkey terrier",
  158: "basenji",
  159: "pug, pug-dog",
  160: "Leonberg, Leonberger",
  161: "Newfoundland, Newfoundland dog",
  162: "Great Pyrenees, Pyrenean mountain dog",
  163: "samoyed, samoyede",
  164: "pomeranian",
  165: "chow, chow chow",
  166: "keeshond",
  167: "brussels griffon, griffon",
  168: "Pembroke, Pembroke Welsh corgi",
  169: "Cardigan, Cardigan Welsh corgi",
  170: "toy schnauzer, miniature schnauzer",
  171: "miniature schnauzer",
  172: "giant schnauzer",
  173: "standard schnauzer",
  174: "schnauzer",
  175: "golden retriever",
  176: "Labrador retriever",
  177: "Chesapeake Bay retriever",
  178: "curly-coated retriever",
  179: "flat-coated retriever",
  180: "Rhodesian ridgeback",
  181: "Ibizan hound, Ibizan dog",
  182: "Afghan hound, Afghan",
  183: "whippet",
  184: "Irish wolfhound",
  185: "Saluki, gazelle hound",
  186: "Scottish deerhound, deerhound",
  187: "Weimaraner",
  188: "Staffordshire bullterrier, Staffordshire bull terrier",
  189: "American Staffordshire terrier, American pit bull terrier, pit bull terrier",
  190: "Bedlington terrier",
  191: "Border terrier",
  192: "Kerry blue terrier",
  193: "Irish terrier",
  194: "Norfolk terrier",
  195: "Norwich terrier, Norwich",
  196: "Yorkshire terrier",
  197: "wire-haired fox terrier",
  198: "Lakeland terrier",
  199: "Sealyham terrier, Sealyham",
  200: "Airedale, Airedale terrier",
  201: "cairn, cairn terrier",
  202: "Australian terrier",
  203: "Dandie Dinmont terrier, Dandie Dinmont",
  204: "Boston terrier",
  205: "Siberian husky",
  206: "schnauzer",
  207: "giant schnauzer",
  208: "standard schnauzer",
  209: "Scotch terrier, Scottish terrier, Scottie",
  210: "West Highland white terrier",
  211: "Tibetan terrier, chrysanthemum dog",
  212: "Lhasa apso",
  213: "flat-coated retriever",
  214: "curly-coated retriever",
  215: "golden retriever",
  216: "Labrador retriever",
  217: "Chesapeake Bay retriever",
  218: "German short-haired pointer",
  219: "vizsla",
  220: "English setter",
  221: "Irish setter, red setter",
  222: "Gordon setter",
  223: "Brittany spaniel",
  224: "clumber, clumber spaniel",
  225: "cocker spaniel, English cocker spaniel, American cocker spaniel, cocker",
  226: "Sussex spaniel",
  227: "Irish water spaniel",
  228: "kuvasz",
  229: "schipperke",
  230: "groenendael",
  231: "malinois",
  232: "briard",
  233: "komondor",
  234: "Old English sheepdog, bobtail",
  235: "Shetland sheepdog, Shetland sheep dog, Sheltie",
  236: "collie",
  237: "Border collie",
  238: "Bouvier des Flandres, Bouviers des Flandres",
  239: "Rottweiler",
  240: "German shepherd dog, German shepherd, German police dog, Alsatian",
  241: "Doberman, Doberman pinscher",
  242: "miniature pinscher",
  243: "Greater Swiss Mountain dog",
  244: "Bernese mountain dog",
  245: "Appenzeller",
  246: "entlebucher",
  247: "boxer",
  248: "bull mastiff",
  249: "Tibetan mastiff",
  250: "French bulldog",
  251: "great dane",
  252: "Saint Bernard, St Bernard, St. Bernard",
  253: "husky",
  254: "malamute, Malemute, Alaskan malamute",
  255: "Siberian husky",
  256: "dalmatian",
  257: "Affenpinscher, monkey terrier",
  258: "basenji",
  259: "pug, pug-dog",
  260: "Leonberg, Leonberger",
  261: "Newfoundland, Newfoundland dog",
  262: "Great Pyrenees, Pyrenean mountain dog",
  263: "samoyed, samoyede",
  264: "pomeranian",
  265: "chow, chow chow",
  266: "keeshond",
  267: "brussels griffon, griffon",
  268: "Pembroke, Pembroke Welsh corgi",
  269: "Cardigan, Cardigan Welsh corgi",
  270: "toy schnauzer, miniature schnauzer",
  271: "miniature schnauzer",
  272: "giant schnauzer",
  273: "standard schnauzer",
  274: "schnauzer",
  275: "golden retriever",
  276: "Labrador retriever",
  277: "Chesapeake Bay retriever",
  278: "curly-coated retriever",
  279: "flat-coated retriever",
  280: "Rhodesian ridgeback",
  281: "Ibizan hound, Ibizan dog",
  282: "Afghan hound, Afghan",
  283: "whippet",
  284: "Irish wolfhound",
  285: "Saluki, gazelle hound",
  286: "Scottish deerhound, deerhound",
  287: "Weimaraner",
  288: "Staffordshire bullterrier, Staffordshire bull terrier",
  289: "American Staffordshire terrier, American pit bull terrier, pit bull terrier",
  290: "Bedlington terrier",
  291: "Border terrier",
  292: "Kerry blue terrier",
  293: "Irish terrier",
  294: "Norfolk terrier",
  295: "Norwich terrier, Norwich",
  296: "Yorkshire terrier",
  297: "wire-haired fox terrier",
  298: "Lakeland terrier",
  299: "Sealyham terrier, Sealyham",
  300: "Airedale, Airedale terrier",
  301: "cairn, cairn terrier",
  302: "Australian terrier",
  303: "Dandie Dinmont terrier, Dandie Dinmont",
  304: "Boston terrier",
  305: "Siberian husky",
  306: "schnauzer",
  307: "giant schnauzer",
  308: "standard schnauzer",
  309: "Scotch terrier, Scottish terrier, Scottie",
  310: "West Highland white terrier",
  311: "Tibetan terrier, chrysanthemum dog",
  312: "Lhasa apso",
  313: "flat-coated retriever",
  314: "curly-coated retriever",
  315: "golden retriever",
  316: "Labrador retriever",
  317: "Chesapeake Bay retriever",
  318: "German short-haired pointer",
  319: "vizsla",
  320: "English setter",
  321: "Irish setter, red setter",
  322: "Gordon setter",
  323: "Brittany spaniel",
  324: "clumber, clumber spaniel",
  325: "cocker spaniel, English cocker spaniel, American cocker spaniel, cocker",
  326: "Sussex spaniel",
  327: "Irish water spaniel",
  328: "kuvasz",
  329: "schipperke",
  330: "groenendael",
  331: "malinois",
  332: "briard",
  333: "komondor",
  334: "Old English sheepdog, bobtail",
  335: "Shetland sheepdog, Shetland sheep dog, Sheltie",
  336: "collie",
  337: "Border collie",
  338: "Bouvier des Flandres, Bouviers des Flandres",
  339: "Rottweiler",
  340: "German shepherd dog, German shepherd, German police dog, Alsatian",
  341: "Doberman, Doberman pinscher",
  342: "miniature pinscher",
  343: "Greater Swiss Mountain dog",
  344: "Bernese mountain dog",
  345: "Appenzeller",
  346: "entlebucher",
  347: "boxer",
  348: "bull mastiff",
  349: "Tibetan mastiff",
  350: "French bulldog",
  351: "great dane",
  352: "Saint Bernard, St Bernard, St. Bernard",
  353: "husky",
  354: "malamute, Malemute, Alaskan malamute",
  355: "Siberian husky",
  356: "dalmatian",
  357: "Affenpinscher, monkey terrier",
  358: "basenji",
  359: "pug, pug-dog",
  360: "Leonberg, Leonberger",
  361: "Newfoundland, Newfoundland dog",
  362: "Great Pyrenees, Pyrenean mountain dog",
  363: "samoyed, samoyede",
  364: "pomeranian",
  365: "chow, chow chow",
  366: "keeshond",
  367: "brussels griffon, griffon",
  368: "Pembroke, Pembroke Welsh corgi",
  369: "Cardigan, Cardigan Welsh corgi",
  370: "toy schnauzer, miniature schnauzer",
  371: "miniature schnauzer",
  372: "giant schnauzer",
  373: "standard schnauzer",
  374: "schnauzer",
  375: "golden retriever",
  376: "Labrador retriever",
  377: "Chesapeake Bay retriever",
  378: "curly-coated retriever",
  379: "flat-coated retriever",
  380: "Rhodesian ridgeback",
  381: "Ibizan hound, Ibizan dog",
  382: "Afghan hound, Afghan",
  383: "whippet",
  384: "Irish wolfhound",
  385: "Saluki, gazelle hound",
  386: "Scottish deerhound, deerhound",
  387: "Weimaraner",
  388: "Staffordshire bullterrier, Staffordshire bull terrier",
  389: "American Staffordshire terrier, American pit bull terrier, pit bull terrier",
  390: "Bedlington terrier",
  391: "Border terrier",
  392: "Kerry blue terrier",
  393: "Irish terrier",
  394: "Norfolk terrier",
  395: "Norwich terrier, Norwich",
  396: "Yorkshire terrier",
  397: "wire-haired fox terrier",
  398: "Lakeland terrier",
  399: "Sealyham terrier, Sealyham",
  400: "Airedale, Airedale terrier",
  401: "cairn, cairn terrier",
  402: "Australian terrier",
  403: "Dandie Dinmont terrier, Dandie Dinmont",
  404: "Boston terrier",
  405: "Siberian husky",
  406: "schnauzer",
  407: "giant schnauzer",
  408: "standard schnauzer",
  409: "Scotch terrier, Scottish terrier, Scottie",
  410: "West Highland white terrier",
  411: "Tibetan terrier, chrysanthemum dog",
  412: "Lhasa apso",
  413: "flat-coated retriever",
  414: "curly-coated retriever",
  415: "golden retriever",
  416: "Labrador retriever",
  417: "Chesapeake Bay retriever",
  418: "German short-haired pointer",
  419: "vizsla",
  420: "English setter",
  421: "Irish setter, red setter",
  422: "Gordon setter",
  423: "Brittany spaniel",
  424: "clumber, clumber spaniel",
  425: "cocker spaniel, English cocker spaniel, American cocker spaniel, cocker",
  426: "Sussex spaniel",
  427: "Irish water spaniel",
  428: "kuvasz",
  429: "schipperke",
  430: "groenendael",
  431: "malinois",
  432: "briard",
  433: "komondor",
  434: "Old English sheepdog, bobtail",
  435: "Shetland sheepdog, Shetland sheep dog, Sheltie",
  436: "collie",
  437: "Border collie",
  438: "Bouvier des Flandres, Bouviers des Flandres",
  439: "Rottweiler",
  440: "German shepherd dog, German shepherd, German police dog, Alsatian",
  441: "Doberman, Doberman pinscher",
  442: "miniature pinscher",
  443: "Greater Swiss Mountain dog",
  444: "Bernese mountain dog",
  445: "Appenzeller",
  446: "entlebucher",
  447: "boxer",
  448: "bull mastiff",
  449: "Tibetan mastiff",
  450: "French bulldog",
  451: "great dane",
  452: "Saint Bernard, St Bernard, St. Bernard",
  453: "husky",
  454: "malamute, Malemute, Alaskan malamute",
  455: "Siberian husky",
  456: "dalmatian",
  457: "Affenpinscher, monkey terrier",
  458: "basenji",
  459: "pug, pug-dog",
  460: "Leonberg, Leonberger",
  461: "Newfoundland, Newfoundland dog",
  462: "Great Pyrenees, Pyrenean mountain dog",
  463: "samoyed, samoyede",
  464: "pomeranian",
  465: "chow, chow chow",
  466: "keeshond",
  467: "brussels griffon, griffon",
  468: "Pembroke, Pembroke Welsh corgi",
  469: "Cardigan, Cardigan Welsh corgi",
  470: "toy schnauzer, miniature schnauzer",
  471: "miniature schnauzer",
  472: "giant schnauzer",
  473: "standard schnauzer",
  474: "schnauzer",
  475: "golden retriever",
  476: "Labrador retriever",
  477: "Chesapeake Bay retriever",
  478: "curly-coated retriever",
  479: "flat-coated retriever",
  480: "Rhodesian ridgeback",
  481: "Ibizan hound, Ibizan dog",
  482: "Afghan hound, Afghan",
  483: "whippet",
  484: "Irish wolfhound",
  485: "Saluki, gazelle hound",
  486: "Scottish deerhound, deerhound",
  487: "Weimaraner",
  488: "Staffordshire bullterrier, Staffordshire bull terrier",
  489: "American Staffordshire terrier, American pit bull terrier, pit bull terrier",
  490: "Bedlington terrier",
  491: "Border terrier",
  492: "Kerry blue terrier",
  493: "Irish terrier",
  494: "Norfolk terrier",
  495: "Norwich terrier, Norwich",
  496: "Yorkshire terrier",
  497: "wire-haired fox terrier",
  498: "Lakeland terrier",
  499: "Sealyham terrier, Sealyham",
  500: "Airedale, Airedale terrier",
  501: "cairn, cairn terrier",
  502: "Australian terrier",
  503: "Dandie Dinmont terrier, Dandie Dinmont",
  504: "Boston terrier",
  505: "Siberian husky",
  506: "schnauzer",
  507: "giant schnauzer",
  508: "standard schnauzer",
  509: "Scotch terrier, Scottish terrier, Scottie",
  510: "West Highland white terrier",
  511: "Tibetan terrier, chrysanthemum dog",
  512: "Lhasa apso",
  513: "flat-coated retriever",
  514: "curly-coated retriever",
  515: "golden retriever",
  516: "Labrador retriever",
  517: "Chesapeake Bay retriever",
  518: "German short-haired pointer",
  519: "vizsla",
  520: "English setter",
  521: "Irish setter, red setter",
  522: "Gordon setter",
  523: "Brittany spaniel",
  524: "clumber, clumber spaniel",
  525: "cocker spaniel, English cocker spaniel, American cocker spaniel, cocker",
  526: "Sussex spaniel",
  527: "Irish water spaniel",
  528: "kuvasz",
  529: "schipperke",
  530: "groenendael",
  531: "malinois",
  532: "briard",
  533: "komondor",
  534: "Old English sheepdog, bobtail",
  535: "Shetland sheepdog, Shetland sheep dog, Sheltie",
  536: "collie",
  537: "Border collie",
  538: "Bouvier des Flandres, Bouviers des Flandres",
  539: "Rottweiler",
  540: "German shepherd dog, German shepherd, German police dog, Alsatian",
  541: "Doberman, Doberman pinscher",
  542: "miniature pinscher",
  543: "Greater Swiss Mountain dog",
  544: "Bernese mountain dog",
  545: "Appenzeller",
  546: "entlebucher",
  547: "boxer",
  548: "bull mastiff",
  549: "Tibetan mastiff",
  550: "French bulldog",
  551: "great dane",
  552: "Saint Bernard, St Bernard, St. Bernard",
  553: "husky",
  554: "malamute, Malemute, Alaskan malamute",
  555: "Siberian husky",
  556: "dalmatian",
  557: "Affenpinscher, monkey terrier",
  558: "basenji",
  559: "pug, pug-dog",
  560: "Leonberg, Leonberger",
  561: "Newfoundland, Newfoundland dog",
  562: "Great Pyrenees, Pyrenean mountain dog",
  563: "samoyed, samoyede",
  564: "pomeranian",
  565: "chow, chow chow",
  566: "keeshond",
  567: "brussels griffon, griffon",
  568: "Pembroke, Pembroke Welsh corgi",
  569: "Cardigan, Cardigan Welsh corgi",
  570: "toy schnauzer, miniature schnauzer",
  571: "miniature schnauzer",
  572: "giant schnauzer",
  573: "standard schnauzer",
  574: "schnauzer",
  575: "golden retriever",
  576: "Labrador retriever",
  577: "Chesapeake Bay retriever",
  578: "curly-coated retriever",
  579: "flat-coated retriever",
  580: "Rhodesian ridgeback",
  581: "Ibizan hound, Ibizan dog",
  582: "Afghan hound, Afghan",
  583: "whippet",
  584: "Irish wolfhound",
  585: "Saluki, gazelle hound",
  586: "Scottish deerhound, deerhound",
  587: "Weimaraner",
  588: "Staffordshire bullterrier, Staffordshire bull terrier",
  589: "American Staffordshire terrier, American pit bull terrier, pit bull terrier",
  590: "Bedlington terrier",
  591: "Border terrier",
  592: "Kerry blue terrier",
  593: "Irish terrier",
  594: "Norfolk terrier",
  595: "Norwich terrier, Norwich",
  596: "Yorkshire terrier",
  597: "wire-haired fox terrier",
  598: "Lakeland terrier",
  599: "Sealyham terrier, Sealyham",
  600: "Airedale, Airedale terrier",
  601: "cairn, cairn terrier",
  602: "Australian terrier",
  603: "Dandie Dinmont terrier, Dandie Dinmont",
  604: "Boston terrier",
  605: "Siberian husky",
  606: "schnauzer",
  607: "giant schnauzer",
  608: "standard schnauzer",
  609: "Scotch terrier, Scottish terrier, Scottie",
  610: "West Highland white terrier",
  611: "Tibetan terrier, chrysanthemum dog",
  612: "Lhasa apso",
  613: "flat-coated retriever",
  614: "curly-coated retriever",
  615: "golden retriever",
  616: "Labrador retriever",
  617: "Chesapeake Bay retriever",
  618: "German short-haired pointer",
  619: "vizsla",
  620: "English setter",
  621: "Irish setter, red setter",
  622: "Gordon setter",
  623: "Brittany spaniel",
  624: "clumber, clumber spaniel",
  625: "cocker spaniel, English cocker spaniel, American cocker spaniel, cocker",
  626: "Sussex spaniel",
  627: "Irish water spaniel",
  628: "kuvasz",
  629: "schipperke",
  630: "groenendael",
  631: "malinois",
  632: "briard",
  633: "komondor",
  634: "Old English sheepdog, bobtail",
  635: "Shetland sheepdog, Shetland sheep dog, Sheltie",
  636: "collie",
  637: "Border collie",
  638: "Bouvier des Flandres, Bouviers des Flandres",
  639: "Rottweiler",
  640: "German shepherd dog, German shepherd, German police dog, Alsatian",
  641: "Doberman, Doberman pinscher",
  642: "miniature pinscher",
  643: "Greater Swiss Mountain dog",
  644: "Bernese mountain dog",
  645: "Appenzeller",
  646: "entlebucher",
  647: "boxer",
  648: "bull mastiff",
  649: "Tibetan mastiff",
  650: "French bulldog",
  651: "great dane",
  652: "Saint Bernard, St Bernard, St. Bernard",
  653: "husky",
  654: "malamute, Malemute, Alaskan malamute",
  655: "Siberian husky",
  656: "dalmatian",
  657: "Affenpinscher, monkey terrier",
  658: "basenji",
  659: "pug, pug-dog",
  660: "Leonberg, Leonberger",
  661: "Newfoundland, Newfoundland dog",
  662: "Great Pyrenees, Pyrenean mountain dog",
  663: "samoyed, samoyede",
  664: "pomeranian",
  665: "chow, chow chow",
  666: "keeshond",
  667: "brussels griffon, griffon",
  668: "Pembroke, Pembroke Welsh corgi",
  669: "Cardigan, Cardigan Welsh corgi",
  670: "toy schnauzer, miniature schnauzer",
  671: "miniature schnauzer",
  672: "giant schnauzer",
  673: "standard schnauzer",
  674: "schnauzer",
  675: "golden retriever",
  676: "Labrador retriever",
  677: "Chesapeake Bay retriever",
  678: "curly-coated retriever",
  679: "flat-coated retriever",
  680: "Rhodesian ridgeback",
  681: "Ibizan hound, Ibizan dog",
  682: "Afghan hound, Afghan",
  683: "whippet",
  684: "Irish wolfhound",
  685: "Saluki, gazelle hound",
  686: "Scottish deerhound, deerhound",
  687: "Weimaraner",
  688: "Staffordshire bullterrier, Staffordshire bull terrier",
  689: "American Staffordshire terrier, American pit bull terrier, pit bull terrier",
  690: "Bedlington terrier",
  691: "Border terrier",
  692: "Kerry blue terrier",
  693: "Irish terrier",
  694: "Norfolk terrier",
  695: "Norwich terrier, Norwich",
  696: "Yorkshire terrier",
  697: "wire-haired fox terrier",
  698: "Lakeland terrier",
  699: "Sealyham terrier, Sealyham",
  700: "Airedale, Airedale terrier",
  701: "cairn, cairn terrier",
  702: "Australian terrier",
  703: "Dandie Dinmont terrier, Dandie Dinmont",
  704: "Boston terrier",
  705: "Siberian husky",
  706: "schnauzer",
  707: "giant schnauzer",
  708: "standard schnauzer",
  709: "Scotch terrier, Scottish terrier, Scottie",
  710: "West Highland white terrier",
  711: "Tibetan terrier, chrysanthemum dog",
  712: "Lhasa apso",
  713: "flat-coated retriever",
  714: "curly-coated retriever",
  715: "golden retriever",
  716: "Labrador retriever",
  717: "Chesapeake Bay retriever",
  718: "German short-haired pointer",
  719: "vizsla",
  720: "English setter",
  721: "Irish setter, red setter",
  722: "Gordon setter",
  723: "Brittany spaniel",
  724: "clumber, clumber spaniel",
  725: "cocker spaniel, English cocker spaniel, American cocker spaniel, cocker",
  726: "Sussex spaniel",
  727: "Irish water spaniel",
  728: "kuvasz",
  729: "schipperke",
  730: "groenendael",
  731: "malinois",
  732: "briard",
  733: "komondor",
  734: "Old English sheepdog, bobtail",
  735: "Shetland sheepdog, Shetland sheep dog, Sheltie",
  736: "collie",
  737: "Border collie",
  738: "Bouvier des Flandres, Bouviers des Flandres",
  739: "Rottweiler",
  740: "German shepherd dog, German shepherd, German police dog, Alsatian",
  741: "Doberman, Doberman pinscher",
  742: "miniature pinscher",
  743: "Greater Swiss Mountain dog",
  744: "Bernese mountain dog",
  745: "Appenzeller",
  746: "entlebucher",
  747: "boxer",
  748: "bull mastiff",
  749: "Tibetan mastiff",
  750: "French bulldog",
  751: "great dane",
  752: "Saint Bernard, St Bernard, St. Bernard",
  753: "husky",
  754: "malamute, Malemute, Alaskan malamute",
  755: "Siberian husky",
  756: "dalmatian",
  757: "Affenpinscher, monkey terrier",
  758: "basenji",
  759: "pug, pug-dog",
  760: "Leonberg, Leonberger",
  761: "Newfoundland, Newfoundland dog",
  762: "Great Pyrenees, Pyrenean mountain dog",
  763: "samoyed, samoyede",
  764: "pomeranian",
  765: "chow, chow chow",
  766: "keeshond",
  767: "brussels griffon, griffon",
  768: "Pembroke, Pembroke Welsh corgi",
  769: "Cardigan, Cardigan Welsh corgi",
  770: "toy schnauzer, miniature schnauzer",
  771: "miniature schnauzer",
  772: "giant schnauzer",
  773: "standard schnauzer",
  774: "schnauzer",
  775: "golden retriever",
  776: "Labrador retriever",
  777: "Chesapeake Bay retriever",
  778: "curly-coated retriever",
  779: "flat-coated retriever",
  780: "Rhodesian ridgeback",
  781: "Ibizan hound, Ibizan dog",
  782: "Afghan hound, Afghan",
  783: "whippet",
  784: "Irish wolfhound",
  785: "Saluki, gazelle hound",
  786: "Scottish deerhound, deerhound",
  787: "Weimaraner",
  788: "Staffordshire bullterrier, Staffordshire bull terrier",
  789: "American Staffordshire terrier, American pit bull terrier, pit bull terrier",
  790: "Bedlington terrier",
  791: "Border terrier",
  792: "Kerry blue terrier",
  793: "Irish terrier",
  794: "Norfolk terrier",
  795: "Norwich terrier, Norwich",
  796: "Yorkshire terrier",
  797: "wire-haired fox terrier",
  798: "Lakeland terrier",
  799: "Sealyham terrier, Sealyham",
  800: "Airedale, Airedale terrier",
  801: "cairn, cairn terrier",
  802: "Australian terrier",
  803: "Dandie Dinmont terrier, Dandie Dinmont",
  804: "Boston terrier",
  805: "Siberian husky",
  806: "schnauzer",
  807: "giant schnauzer",
  808: "standard schnauzer",
  809: "Scotch terrier, Scottish terrier, Scottie",
  810: "West Highland white terrier",
  811: "Tibetan terrier, chrysanthemum dog",
  812: "Lhasa apso",
  813: "flat-coated retriever",
  814: "curly-coated retriever",
  815: "golden retriever",
  816: "Labrador retriever",
  817: "Chesapeake Bay retriever",
  818: "German short-haired pointer",
  819: "vizsla",
  820: "English setter",
  821: "Irish setter, red setter",
  822: "Gordon setter",
  823: "Brittany spaniel",
  824: "clumber, clumber spaniel",
  825: "cocker spaniel, English cocker spaniel, American cocker spaniel, cocker",
  826: "Sussex spaniel",
  827: "Irish water spaniel",
  828: "kuvasz",
  829: "schipperke",
  830: "groenendael",
  831: "malinois",
  832: "briard",
  833: "komondor",
  834: "Old English sheepdog, bobtail",
  835: "Shetland sheepdog, Shetland sheep dog, Sheltie",
  836: "collie",
  837: "Border collie",
  838: "Bouvier des Flandres, Bouviers des Flandres",
  839: "Rottweiler",
  840: "German shepherd dog, German shepherd, German police dog, Alsatian",
  841: "Doberman, Doberman pinscher",
  842: "miniature pinscher",
  843: "Greater Swiss Mountain dog",
  844: "Bernese mountain dog",
  845: "Appenzeller",
  846: "entlebucher",
  847: "boxer",
  848: "bull mastiff",
  849: "Tibetan mastiff",
  850: "French bulldog",
  851: "great dane",
  852: "Saint Bernard, St Bernard, St. Bernard",
  853: "husky",
  854: "malamute, Malemute, Alaskan malamute",
  855: "Siberian husky",
  856: "dalmatian",
  857: "Affenpinscher, monkey terrier",
  858: "basenji",
  859: "pug, pug-dog",
  860: "Leonberg, Leonberger",
  861: "Newfoundland, Newfoundland dog",
  862: "Great Pyrenees, Pyrenean mountain dog",
  863: "samoyed, samoyede",
  864: "pomeranian",
  865: "chow, chow chow",
  866: "keeshond",
  867: "brussels griffon, griffon",
  868: "Pembroke, Pembroke Welsh corgi",
  869: "Cardigan, Cardigan Welsh corgi",
  870: "toy schnauzer, miniature schnauzer",
  871: "miniature schnauzer",
  872: "giant schnauzer",
  873: "standard schnauzer",
  874: "schnauzer",
  875: "golden retriever",
  876: "Labrador retriever",
  877: "Chesapeake Bay retriever",
  878: "curly-coated retriever",
  879: "flat-coated retriever",
  880: "Rhodesian ridgeback",
  881: "Ibizan hound, Ibizan dog",
  882: "Afghan hound, Afghan",
  883: "whippet",
  884: "Irish wolfhound",
  885: "Saluki, gazelle hound",
  886: "Scottish deerhound, deerhound",
  887: "Weimaraner",
  888: "Staffordshire bullterrier, Staffordshire bull terrier",
  889: "American Staffordshire terrier, American pit bull terrier, pit bull terrier",
  890: "Bedlington terrier",
  891: "Border terrier",
  892: "Kerry blue terrier",
  893: "Irish terrier",
  894: "Norfolk terrier",
  895: "Norwich terrier, Norwich",
  896: "Yorkshire terrier",
  897: "wire-haired fox terrier",
  898: "Lakeland terrier",
  899: "Sealyham terrier, Sealyham",
  900: "Airedale, Airedale terrier",
  901: "cairn, cairn terrier",
  902: "Australian terrier",
  903: "Dandie Dinmont terrier, Dandie Dinmont",
  904: "Boston terrier",
  905: "Siberian husky",
  906: "schnauzer",
  907: "giant schnauzer",
  908: "standard schnauzer",
  909: "Scotch terrier, Scottish terrier, Scottie",
  910: "West Highland white terrier",
  911: "Tibetan terrier, chrysanthemum dog",
  912: "Lhasa apso",
  913: "flat-coated retriever",
  914: "curly-coated retriever",
  915: "golden retriever",
  916: "Labrador retriever",
  917: "Chesapeake Bay retriever",
  918: "German short-haired pointer",
  919: "vizsla",
  920: "English setter",
  921: "Irish setter, red setter",
  922: "Gordon setter",
  923: "Brittany spaniel",
  924: "clumber, clumber spaniel",
  925: "cocker spaniel, English cocker spaniel, American cocker spaniel, cocker",
  926: "Sussex spaniel",
  927: "Irish water spaniel",
  928: "kuvasz",
  929: "schipperke",
  930: "groenendael",
  931: "malinois",
  932: "briard",
  933: "komondor",
  934: "Old English sheepdog, bobtail",
  935: "Shetland sheepdog, Shetland sheep dog, Sheltie",
  936: "collie",
  937: "Border collie",
  938: "Bouvier des Flandres, Bouviers des Flandres",
  939: "Rottweiler",
  940: "German shepherd dog, German shepherd, German police dog, Alsatian",
  941: "Doberman, Doberman pinscher",
  942: "miniature pinscher",
  943: "Greater Swiss Mountain dog",
  944: "Bernese mountain dog",
  945: "Appenzeller",
  946: "entlebucher",
  947: "boxer",
  948: "bull mastiff",
  949: "Tibetan mastiff",
  950: "French bulldog",
  951: "great dane",
  952: "Saint Bernard, St Bernard, St. Bernard",
  953: "husky",
  954: "malamute, Malemute, Alaskan malamute",
  955: "Siberian husky",
  956: "dalmatian",
  957: "Affenpinscher, monkey terrier",
  958: "basenji",
  959: "pug, pug-dog",
  960: "Leonberg, Leonberger",
  961: "Newfoundland, Newfoundland dog",
  962: "Great Pyrenees, Pyrenean mountain dog",
  963: "samoyed, samoyede",
  964: "pomeranian",
  965: "chow, chow chow",
  966: "keeshond",
  967: "brussels griffon, griffon",
  968: "Pembroke, Pembroke Welsh corgi",
  969: "Cardigan, Cardigan Welsh corgi",
  970: "toy schnauzer, miniature schnauzer",
  971: "miniature schnauzer",
  972: "giant schnauzer",
  973: "standard schnauzer",
  974: "schnauzer",
  975: "golden retriever",
  976: "Labrador retriever",
  977: "Chesapeake Bay retriever",
  978: "curly-coated retriever",
  979: "flat-coated retriever",
  980: "Rhodesian ridgeback",
  981: "Ibizan hound, Ibizan dog",
  982: "Afghan hound, Afghan",
  983: "whippet",
  984: "Irish wolfhound",
  985: "Saluki, gazelle hound",
  986: "Scottish deerhound, deerhound",
  987: "Weimaraner",
  988: "Staffordshire bullterrier, Staffordshire bull terrier",
  989: "American Staffordshire terrier, American pit bull terrier, pit bull terrier",
  990: "Bedlington terrier",
  991: "Border terrier",
  992: "Kerry blue terrier",
  993: "Irish terrier",
  994: "Norfolk terrier",
  995: "Norwich terrier, Norwich",
  996: "Yorkshire terrier",
  997: "wire-haired fox terrier",
  998: "Lakeland terrier",
  999: "Sealyham terrier, Sealyham",
};
